services:
  gestion-volets:
    build: .
    container_name: gestion-volets
    ports:
      - "3157:3000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - homeassistant_gestion_volets
    environment:
      - NODE_ENV=production

networks:
  homeassistant_gestion_volets:
    driver: bridge 